spring.datasource.url=jdbc:mysql://localhost/foro_alura_api
spring.datasource.username=root
spring.datasource.password=angel126

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.front_sql=true

